# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-18 12:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chequeApp', '0002_auto_20160811_1336'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='docfile',
            field=models.FileField(upload_to='document/%m/%y/%d'),
        ),
    ]
