# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-03 07:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chequeApp', '0004_bodataupload_uccdataupload'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='docfile',
            field=models.FileField(upload_to='document/'),
        ),
    ]
