# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-17 08:53
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('chequeApp', '0005_auto_20160903_1249'),
    ]

    operations = [
        migrations.AddField(
            model_name='uccdataupload',
            name='name',
            field=models.CharField(default=datetime.datetime(2016, 9, 17, 8, 53, 58, 416912, tzinfo=utc), max_length=25),
            preserve_default=False,
        ),
    ]
