# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-17 08:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chequeApp', '0006_uccdataupload_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='uccdataupload',
            old_name='name',
            new_name='name1',
        ),
    ]
