# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-17 09:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chequeApp', '0007_auto_20160917_1427'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uccdataupload',
            name='name1',
        ),
    ]
