# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-17 09:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chequeApp', '0008_remove_uccdataupload_name1'),
    ]

    operations = [
        migrations.AddField(
            model_name='uccdataupload',
            name='name1',
            field=models.CharField(default='', max_length=100),
        ),
    ]
